"""комментарий2

Revision ID: 6e84be2b44a1
Revises: 72f28756dac9
Create Date: 2025-09-04 23:14:13.528749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e84be2b44a1'
down_revision: Union[str, Sequence[str], None] = '72f28756dac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('cadastral_id', sa.Integer(), nullable=False, comment='ID Кадастровый номер.'))
    op.drop_constraint(op.f('history_cadastral_number_key'), 'history', type_='unique')
    op.drop_constraint(op.f('history_request_id_fkey'), 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'requestmodel', ['cadastral_id'], ['id'], ondelete='CASCADE')
    op.drop_column('history', 'cadastral_number')
    op.drop_column('history', 'request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID запроса, на который ссылается история.'))
    op.add_column('history', sa.Column('cadastral_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Кадастровый номер.'))
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key(op.f('history_request_id_fkey'), 'history', 'requestmodel', ['request_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('history_cadastral_number_key'), 'history', ['cadastral_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('history', 'cadastral_id')
    # ### end Alembic commands ###
