"""комментарий1

Revision ID: 72f28756dac9
Revises: 4932c7a4ceff
Create Date: 2025-09-04 23:12:34.194517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f28756dac9'
down_revision: Union[str, Sequence[str], None] = '4932c7a4ceff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('request_id', sa.Integer(), nullable=False, comment='ID запроса, на который ссылается история.'))
    op.create_foreign_key(None, 'history', 'requestmodel', ['request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'request_id')
    # ### end Alembic commands ###
