"""комментарий5

Revision ID: b4abd1df17a4
Revises: dc82bd59cd65
Create Date: 2025-09-05 00:16:00.952293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4abd1df17a4'
down_revision: Union[str, Sequence[str], None] = 'dc82bd59cd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('status', sa.Boolean(), nullable=True, comment='Результат запроса.'))
    op.drop_column('requestmodel', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestmodel', sa.Column('result', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Результат запроса.'))
    op.drop_column('history', 'status')
    # ### end Alembic commands ###
