"""комментарий к миграции

Revision ID: c7bfa6646065
Revises: 
Create Date: 2025-09-02 21:37:56.745561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bfa6646065'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestmodel',
    sa.Column('cadastral_number', sa.String(length=50), nullable=False, comment='Кадастровый номер.'),
    sa.Column('latitude', sa.Float(precision=50), nullable=False, comment='Широта.'),
    sa.Column('longitude', sa.Float(precision=50), nullable=False, comment='Долгота.'),
    sa.Column('result', sa.Boolean(), nullable=True, comment='Результат запроса.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cadastral_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestmodel')
    # ### end Alembic commands ###
