"""комментарий4

Revision ID: dc82bd59cd65
Revises: 0d290e42012e
Create Date: 2025-09-04 23:39:30.921869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc82bd59cd65'
down_revision: Union[str, Sequence[str], None] = '0d290e42012e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('request_id', sa.Integer(), nullable=False, comment='ID Кадастровый номер.'))
    op.drop_constraint(op.f('history_cadastral_id_fkey'), 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'requestmodel', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_column('history', 'cadastral_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('cadastral_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID Кадастровый номер.'))
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key(op.f('history_cadastral_id_fkey'), 'history', 'requestmodel', ['cadastral_id'], ['id'], ondelete='CASCADE')
    op.drop_column('history', 'request_id')
    # ### end Alembic commands ###
