"""комментарий12

Revision ID: 1d0a96d04ca5
Revises: 
Create Date: 2025-09-07 17:01:07.606237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0a96d04ca5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestmodel',
    sa.Column('cadastral_number', sa.String(length=50), nullable=False, comment='Кадастровый номер.'),
    sa.Column('latitude', sa.Float(precision=50), nullable=False, comment='Широта.'),
    sa.Column('longitude', sa.Float(precision=50), nullable=False, comment='Долгота.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cadastral_number')
    )
    op.create_table('history',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи.'),
    sa.Column('request_id', sa.Integer(), nullable=False, comment='ID Кадастровый номер.'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='Результат запроса.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requestmodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('requestmodel')
    # ### end Alembic commands ###
