"""комментарий

Revision ID: 39e080db883f
Revises: 
Create Date: 2025-09-09 22:59:00.171222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e080db883f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestmodel',
    sa.Column('cadastral_number', sa.String(length=50), nullable=False, comment='Кадастровый номер.'),
    sa.Column('latitude', sa.Float(precision=50), nullable=False, comment='Широта.'),
    sa.Column('longitude', sa.Float(precision=50), nullable=False, comment='Долгота.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cadastral_number')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('history',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи.'),
    sa.Column('request_id', sa.String(length=50), nullable=False, comment='ID Кадастровый номер.'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='Результат запроса.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requestmodel.cadastral_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('requestmodel')
    # ### end Alembic commands ###
